matrix:
  include:
    - os: linux
      language: python
      sudo: required
      services:
        - docker
      env: PIP=pip3
      python: 3.5
    - os: osx
      language: generic
      env: PIP=pip3

env:
  global:
  - CIBW_SKIP="cp27-* cp34-*"
  - CIBW_BEFORE_BUILD="pip install pip --upgrade; pip install cython numpy numba --only-binary all"
  - CIBW_BUILD_VERBOSITY="3"
  - TWINE_USERNAME=ashjkelly

script:
  - pip3 install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
  - pip3 install twine
  - python3 -m twine upload wheelhouse/*.whl
