language: python
compiler: gcc
dist: bionic
env:
  global:
    PIP=pip3
    PYTHON=python3

install:
  - |
    $PIP --version
    $PYTHON --version
    $PIP install --upgrade pip
    $PIP install --upgrade setuptools
    $PIP install llvmlite --prefer-binary
    $PIP install numpy cython scipy pytest
    $PIP install -e .

jobs:
  include:
    - stage: tests
      name: "Python: 3.5 tests"
      python: 3.5
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.6 tests"
      python: 3.6
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.7 Tests"
      python: 3.7
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.8 Tests"
      python: 3.8
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.7"
      os: osx
      osx_image: xcode9.4
      language: generic
      env: PIP=pip3
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.8"
      os: osx
      osx_image: xcode10.2
      language: generic
      env: PIP=pip3
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests"
      os: osx
      osx_image: xcode11.3
      language: generic
      env: PIP=pip3
      script: python3 -m pytest tests/
