language: python

sudo: required

dist: xenial

env:
  global:
    PIP=pip

install:
  - |
    $PIP install --upgrade pip
    $PIP install --upgrade setuptools
    $PIP install numpy cython
    $PIP install -e .
    $PIP install scipy pytest

jobs:
  include:
    - stage: tests
      name: "Python: 3.6 Tests"
      python: 3.6
      script: pytest tests/

    - stage: tests
      name: "Python: 3.7 Tests"
      python: 3.7
      script: pytest tests/

    - stage: tests
      name: "Python: 3.8 Tests"
      python: 3.8
      script: pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.7"
      os: osx
      language: generic
      python: 3.7
      env: PIP=pip3
      script: pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.8"
      os: osx
      language: generic
      python: 3.8
      env: PIP=pip3
      script: pytest tests/
