language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    $PIP install --upgrade pip
    $PIP install --upgrade wheel
    $PIP install --upgrade setuptools
    $PIP install numpy
    $PIP install cython
    $PIP install -e .

script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
