language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      env: PIP=pip
    - os: osx
      language: generic
      env: PIP=pip2

env:
  global:
  - CIBW_SKIP="cp27-* cp34-*"
  - CIBW_BEFORE_BUILD="$PIP install cython numpy numba --only-binary all"
  - CIBW_BUILD_VERBOSITY="3"
  - TWINE_USERNAME=ashjkelly

script:
  - "$PIP install cibuildwheel"
  - cibuildwheel --output-dir wheelhouse
  - pip install twine
  - python -m twine upload wheelhouse/*.whl
