language: python

sudo: required
cache:
  pip: false

env:
  global:
    PIP=pip

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    $PIP install --upgrade pip
    $PIP install --upgrade wheel
    $PIP install --upgrade setuptools
    $PIP install numpy
    $PIP install scipy
    $PIP install pytest
    $PIP install -e .

jobs:
  include:
    - stage: tests
      python: 3.7
      script: pytest tests/
  include:
    - stage: tests
      python: 3.6
      script: pytest tests/
  include:
    - stage: tests
      python: 3.5
      script: pytest tests/
