language: python
sudo: required
dist: xenial
cache:
  pip: true
  directories:
    - $HOME/.ccache

addons:
  apt:
    packages:
      - libgsl-dev

matrix:
  include:
    - sudo: required
      services:
        - docker
      python: 3.6
      env: PIP=pip

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    $PIP install --upgrade pip
    $PIP install --upgrade wheel
    $PIP install --upgrade setuptools
    $PIP install numpy
    $PIP install cython
    $PIP install -e .

script:
  - export CIBW_BUILD="cp36-*"
  - export CIBW_BEFORE_BUILD="pip install numpy cython"
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
