jobs:
  include:
    - os: linux
      dist: bionic
      language: python
      services:
        - docker
      env:
        PIP=pip3
        PYTHON=python3
      python: 3.6

    - os: osx
      language: generic
      env:
        PIP=pip3
        PYTHON=python3

env:
  global:
  - CIBW_SKIP="cp27-* cp34-* cp35-* pp27-* pp36-*"
  - CIBW_BEFORE_BUILD="pip install pip --upgrade; pip install cython numpy numba --only-binary all"
  - CIBW_BUILD_VERBOSITY="3"
  - TWINE_USERNAME=ashjkelly

script:
  - $PIP install cibuildwheel==1.4.2
  - cibuildwheel --output-dir wheelhouse
  - $PIP install twine
  - $PYTHON -m twine upload wheelhouse/*.whl
