language: python

matrix:
  include:
    - sudo: required
      services:
        - docker
      python: 3.5
      env:
        - PIP=pip
        - CIBW_BUILD="cp35-*"
        - CIBW_BEFORE_BUILD="pip install numpy"
        - CIBW_BUILD_VERBOSITY="3"

install:
  - |
    # setup environment
    # Upgrade pip and setuptools and wheel to get clean install
    #$PIP install --upgrade pip
    #$PIP install --upgrade wheel
    #$PIP install --upgrade setuptools
    $gcc -v
    $PIP install numpy
    $PIP install -e .


script:
  - $PIP install cibuildwheel
  - cibuildwheel --output-dir wheelhouse
