language: python
dist: xenial
sudo: required
cache:
  pip: true
  directories:
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    PIP=pip

install:
  - |
    # setup environment
    ccache -s
    # Upgrade pip and setuptools and wheel to get clean install
    $PIP install --upgrade pip
    $PIP install --upgrade wheel
    $PIP install --upgrade setuptools
    $PIP install numpy
    $PIP install cython
    $PIP install -e .

jobs:
  include:
    - stage: tests
      python: 3.6
      script: pytest tests/
