language: python
sudo: required
dist: centos
cache:
  pip: false

matrix:
  include:
    - sudo: required
      services:
        - docker
      python: 3.5
      env:
        - PIP=pip
        - CIBW_BUILD="cp35-*"
        - CIBW_BEFORE_BUILD="pip install numpy"
        - CIBW_TEST_COMMAND="auditwheel show /tmp/built_wheel/pyquad-0.0.2.5-cp35-cp35m-linux_x86_64.whl"

install:
  - |
    # setup environment
    # Upgrade pip and setuptools and wheel to get clean install
    #$PIP install --upgrade pip
    #$PIP install --upgrade wheel
    #$PIP install --upgrade setuptools
    $PIP install numpy
    #$PIP install cython
    $PIP install -e .


script:
  #- $PIP install cibuildwheel
  - $PIP install wheel
  - $PIP install numpy
  - /opt/python/cp35-cp35m/bin/pip wheel . -w /tmp/built_wheel --no-deps
  - auditwheel show /tmp/built_wheel/pyquad-0.0.2.5-cp35-cp35m-linux_x86_64.whl
  #- cibuildwheel --output-dir wheelhouse
