matrix:
  include:
    - os: linux
      language: python
      sudo: required
      services:
        - docker
      env: PIP=pip
      python: 3.5
    - os: osx
      language: generic
      env: PIP=pip

env:
  global:
  - CIBW_SKIP="cp27-* cp34-*"
  - CIBW_BEFORE_BUILD="pip install pip --upgrade; pip install cython numpy numba --only-binary all"
  - CIBW_BUILD_VERBOSITY="3"
  - TWINE_USERNAME=ashjkelly

script:
  #- "$PIP install cibuildwheel"
  - pip install git+https://github.com/YannickJadoul/cibuildwheel.git@pip-19-stalling-workaround
  - cibuildwheel --output-dir wheelhouse
  - pip install twine
  - python -m twine upload wheelhouse/*.whl
