language: python

sudo: required

dist: xenial

env:
  global:
    PIP=pip

install:
  - |
    $PIP install --upgrade pip
    $PIP install --upgrade setuptools
    $PIP install numpy cython
    $PIP install -e .
    $PIP install scipy pytest

jobs:
  include:
    - stage: tests
      name: "Python: 3.5 tests"
      python: 3.5
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.6 tests"
      python: 3.6
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.7 Tests"
      python: 3.7
      script: python3 -m pytest tests/

    - stage: tests
      name: "Python: 3.8 Tests"
      python: 3.8
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.5"
      os: osx
      language: generic
      python: 3.5
      env: PIP=pip3
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.6"
      os: osx
      language: generic
      python: 3.6
      env: PIP=pip3
      script: python3 -m pytest tests/

    - stage: tests
      name: "macos: tests 3.7"
      os: osx
      language: generic
      python: 3.7
      env: pip=pip3
      script: python3 -m pytest tests/

    - stage: tests
      name: "MacOS: Tests 3.8"
      os: osx
      language: generic
      python: 3.8
      env: PIP=pip3
      script: python3 -m pytest tests/
